services:
  hose-webpage:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - hose-api

  hose-api:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./server/hose:/app
      - ~/.gradle:/home/gradle/.gradle

  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    command: osrm-routed --algorithm mld /data/ellensburg.osrm
    volumes:
      - ./osrm/data:/data
    ports:
      - "5001:5000"
    networks:
      - backend

  postgres:
    ports:
      - "5432:5432"
