services:
  hose-api:
    restart: unless-stopped

  postgres:
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://hose-api:8080
    restart: unless-stopped
    depends_on:
      - hose-api
    networks:
      - backend

  cloudflared-frontend:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://hose-frontend:80
    restart: unless-stopped
    depends_on:
      - hose-frontend
    networks:
      - backend

  osrm-foot:
    image: osrm-backend-arm
    command: osrm-routed --algorithm mld /data/foot/ellensburg.osrm
    volumes:
      - ./osrm/data:/data
    ports:
      - "5001:5000"
    restart: unless-stopped
    networks:
      - backend

  osrm-bike:
    image: osrm-backend-arm
    command: osrm-routed --algorithm mld /data/bike/ellensburg.osrm
    volumes:
      - ./osrm/data:/data
    ports:
      - "5002:5000"
    restart: unless-stopped
    networks:
      - backend

  osrm-car:
    image: osrm-backend-arm
    command: osrm-routed --algorithm mld /data/car/ellensburg.osrm
    volumes:
      - ./osrm/data:/data
    ports:
      - "5003:5000"
    restart: unless-stopped
    networks:
      - backend
  
