
services:
  # Postgres DB container
  postgres:
    image: postgis/postgis:15-3.3
    container_name: my_postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Flyway service to manage DB and schema
  flyway:
    image: flyway/flyway:10.10.0
    depends_on:
      - postgres
    environment:
      FLYWAY_URL: ${FLYWAY_URL}
      FLYWAY_USER: ${FLYWAY_USER}
      FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
    command: -connectRetries=10 migrate
    volumes:
      - ./database/migrations:/flyway/sql

volumes:
  postgres_data:
